# Generated by Django 3.0.8 on 2020-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0002_auto_20200726_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='patientSex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='male', max_length=6),
        ),
    ]
