# Generated by Django 3.0.8 on 2020-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0003_auto_20200726_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='lastName',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
