# Generated by Django 3.0.8 on 2020-07-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
