# Generated by Django 3.0.8 on 2020-07-31 03:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0007_auto_20200730_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_approver', models.BooleanField(default=False)),
                ('is_data_entry', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profilePicturePath', models.TextField(null=True)),
                ('firstn', models.CharField(max_length=20, null=True)),
                ('lastn', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
