# Generated by Django 3.0.8 on 2020-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0008_auto_20200806_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='patientSex',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
