# Generated by Django 3.0.8 on 2020-07-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0008_auto_20200730_2040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='firstn',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastn',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
