# Generated by Django 3.0.8 on 2020-07-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0009_auto_20200730_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_approver',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_data_entry',
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Approver', 'Approver'), ('Data Entry', 'Data Entry')], default='Admin', max_length=10),
        ),
    ]
