# Generated by Django 3.0.8 on 2020-07-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0010_auto_20200730_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profilePicturePath',
            new_name='profile_picture_path',
        ),
    ]
