# Generated by Django 3.0.8 on 2020-07-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0011_auto_20200731_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
