# Generated by Django 3.0.8 on 2020-08-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0012_auto_20200731_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
